Exception: rewrite dispatcher + fix segfault
- If Exception class isn't member initialized before a calling ctor
function try-block throws, string member manipulation results in
segfault. As such, simply use locals.

- Fixes formatting if dispatch message is missing